### ISSUE TITLE
error by using devtools

### ISSUE THREAD

**Issue by maoyeh** [AllenInstitute/cocoframer#5]
Hi There, I got errors when I do devtools::install_github("AllenInstitute/cocoframer")
Error: object ‘glue_collapse’ is not exported by 'namespace:glue'

**Comment by hypercompetent** [comment]
Hi @maoyeh, 

I'm not able to reproduce this issue, and no functions in cocoframer call the glue_collapse() function. My guess is that this is a devtools issue, as devtools uses glue. Could you try running install.packages("devtools") to try reinstall the devtools package and its dependencies?

**Comment by maoyeh** [comment]
Hi @hypercompetent , Thanks for your quick responses. I am new to R. I tried to update the devtools. And it works. Thanks a lot.

**Comment by hypercompetent** [comment]
Hi @maoyeh,
Glad to hear it worked! Feel free to reach out here or on Twitter (@hypercompetent) if you run into other issues.
Cheers,
-Lucas
